language: scala
scala:
  - 2.11.7
node_js:
  - 0.10

jdk:
  - oraclejdk8

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - "npm install -g bower"
  - "npm install -g gulp-cli"
  - "npm install -g karma"
  - "npm install"
  - "bower install"
  - "gulp buildProdJS"

script:
  - "sbt test"
  - "./node_modules/.bin/karma start ./ui/karma.conf.js --single-run"